// <auto-generated />
using System;
using EmployeeDirectoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDirectoryApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240902171343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDirectoryApi.Models.Employee", b =>
                {
                    b.Property<byte?>("id")
                        .HasColumnType("tinyint");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("casualLeaveAvailable")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("casualLeaveTaken")
                        .HasColumnType("tinyint");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("daysPresent")
                        .HasColumnType("tinyint");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("inHouseExperience")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("leaveApplicationCount")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("leaveApplicationDate")
                        .HasColumnType("date");

                    b.Property<byte?>("leaveApplicationId")
                        .HasColumnType("tinyint");

                    b.Property<string>("leaveApplicationLeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaveApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notesComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("notesDate")
                        .HasColumnType("date");

                    b.Property<byte?>("notesId")
                        .HasColumnType("tinyint");

                    b.Property<string>("notesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("notesTime")
                        .HasColumnType("time");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("probationProgress")
                        .HasColumnType("tinyint");

                    b.Property<double?>("rating")
                        .HasColumnType("float");

                    b.Property<string>("reportingManager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salaryAccessible")
                        .HasColumnType("int");

                    b.Property<int>("salaryPayable")
                        .HasColumnType("int");

                    b.Property<byte?>("sickLeaveAvailable")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("sickLeaveTaken")
                        .HasColumnType("tinyint");

                    b.Property<string>("team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("totalExperience")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("EmployeeDirectoryApi", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
